### PR TITLE
29 determine defaults for package

### PR DESCRIPTION
**Pull request by nikita-jaya**

### CODE REVIEW

**Comment by nikita-jaya** [comment]
`validate_policy()` now does the following in this order:
1. Flattens policy
2. Makes sure each category has at least a "category" and "assignments" argument; if not, throws an error with a message
3. Drops any assignments that are not in gs and any categories with no assignments
4. If none of the assignments are available in gs, returns NULL with a message to the console
5. Adds defaults as specified in the issue

**Comment by andrewpbray** [comment]
How does this PR interact with the other PR? if that was is merged into `main` should we also then merge into this branch to see what the final state of this function would be?

**Comment by nikita-jaya** [comment]
> How does this PR interact with the other PR? if that was is merged into `main` should we also then merge into this branch to see what the final state of this function would be?

With every new PR, I pulled all the stuff from the other PR because everything relied on what was previously coded, so the last PR (chronologically) can be merged into dev/main while having all previous PR work; let me know if I should have used a different approach

**Review by andrewpbray — APPROVED** [review]
beaut!

**Pull request merged**
